services:
  web:
    build: .
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - ./:/usr/app
    depends_on:
      - mongo
      - elastic

  mongo:
    image: mongo:6.0.4-jammy

  elastic:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: ${ELASTIC_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.6.2
    depends_on:
      - elastic
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    mem_limit: ${KIBANA_MEM_LIMIT}
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
